# Generated by Django 4.0.3 on 2022-08-25 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_name', models.CharField(max_length=20, verbose_name='资产名称')),
                ('assets_brand', models.CharField(max_length=20, verbose_name='资产品牌')),
                ('assets_model', models.CharField(max_length=20, verbose_name='资产型号')),
                ('assets_code', models.CharField(max_length=20, verbose_name='资产条码')),
                ('assets_sn', models.CharField(max_length=20, verbose_name='序列号')),
                ('assets_room', models.CharField(max_length=20, verbose_name='所属机房')),
                ('assets_cabinet', models.CharField(max_length=20, verbose_name='所属机柜')),
                ('assets_status', models.CharField(choices=[(1, '在线'), (4, '报废'), (3, '维修'), (2, '在库')], max_length=20, verbose_name='当前状态')),
                ('assets_ip', models.CharField(max_length=20, verbose_name='网管地址')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.project', verbose_name='项目ID')),
            ],
        ),
    ]
