# Generated by Django 4.0.3 on 2022-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(3, '维修'), (1, '在线'), (4, '报废'), (2, '在库')], verbose_name='当前状态'),
        ),
    ]
