# Generated by Django 4.0.3 on 2022-08-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_assets_assets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='assets_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='资产价格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(3, '维修'), (4, '报废'), (2, '在库'), (1, '在线')], verbose_name='当前状态'),
        ),
    ]
