# Generated by Django 4.0.3 on 2022-08-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_assets_assets_price_alter_assets_assets_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(3, '维修'), (2, '在库'), (4, '报废'), (1, '在线')], verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cy_end_date',
            field=models.DateField(verbose_name='项目初验结束时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cy_start_date',
            field=models.DateField(verbose_name='项目初验开始时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lx_end_date',
            field=models.DateField(verbose_name='项目立项结束时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lx_start_date',
            field=models.DateField(verbose_name='项目立项开始时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ss_end_date',
            field=models.DateField(verbose_name='项目实施结束时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ss_start_date',
            field=models.DateField(verbose_name='项目实施开始时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='xq_end_date',
            field=models.DateField(verbose_name='需求分析结束时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='xq_start_date',
            field=models.DateField(verbose_name='需求分析开始时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='zy_end_date',
            field=models.DateField(verbose_name='项目终验结束时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='zy_start_date',
            field=models.DateField(verbose_name='项目终验开始时间'),
        ),
    ]
