# Generated by Django 4.0.3 on 2022-08-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_assets_assets_status_alter_project_cy_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(3, '维修'), (1, '在线'), (4, '报废'), (2, '在库')], verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_used',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='已发生额'),
        ),
    ]
