# Generated by Django 4.0.3 on 2022-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_assets_assets_status_alter_project_amount_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='assets_model',
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_brand',
            field=models.CharField(max_length=20, verbose_name='技术规格'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_cabinet',
            field=models.CharField(max_length=20, null=True, verbose_name='所属机柜'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_ip',
            field=models.CharField(max_length=20, null=True, verbose_name='网管地址'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(2, '在库'), (3, '维修'), (1, '在线'), (4, '报废')], verbose_name='当前状态'),
        ),
    ]
