# Generated by Django 4.0.3 on 2022-08-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_remove_assets_assets_model_alter_assets_assets_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_brand',
            field=models.CharField(max_length=50, verbose_name='技术规格'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_name',
            field=models.CharField(max_length=50, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_room',
            field=models.CharField(max_length=50, verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_sn',
            field=models.CharField(max_length=50, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(1, '在线'), (2, '在库'), (3, '维修'), (4, '报废')], verbose_name='当前状态'),
        ),
    ]
