# Generated by Django 4.0.3 on 2022-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_assets_assets_brand_alter_assets_assets_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_cabinet',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='所属机柜'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='网管地址'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(1, '在线'), (2, '在库'), (4, '报废'), (3, '维修')], verbose_name='当前状态'),
        ),
    ]
