# Generated by Django 4.0.3 on 2022-08-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_assets_assets_date_assets_assets_detail_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=50, verbose_name='合同名称')),
                ('contract_code', models.CharField(max_length=20, verbose_name='合同编号')),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='合同金额')),
                ('apply_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='申购分项预算')),
            ],
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_detail_type',
            field=models.SmallIntegerField(choices=[(2, 'IP网络设备'), (4, '服务器'), (1, '机房基础设备'), (3, '监播设备')], verbose_name='分项类型'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(1, '在线'), (5, '待入库'), (3, '维修'), (2, '在库'), (4, '报废')], verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_total_type',
            field=models.SmallIntegerField(choices=[(2, '软件'), (3, '其他'), (1, '硬件')], verbose_name='总体类型'),
        ),
        migrations.AddField(
            model_name='assets',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.contract', verbose_name='合同ID'),
        ),
    ]
