# Generated by Django 4.0.3 on 2022-08-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_contract_alter_assets_assets_detail_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_detail_type',
            field=models.SmallIntegerField(choices=[(4, '服务器'), (2, 'IP网络设备'), (1, '机房基础设备'), (3, '监播设备')], verbose_name='分项类型'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(5, '待入库'), (3, '维修'), (1, '在线'), (4, '报废'), (2, '在库')], verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_total_type',
            field=models.SmallIntegerField(choices=[(1, '硬件'), (2, '软件'), (3, '其他')], verbose_name='总体类型'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.contract', verbose_name='合同ID'),
            preserve_default=False,
        ),
    ]
