# Generated by Django 4.0.3 on 2022-08-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_assets_assets_detail_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='warehouse_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='已入库金额'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_detail_type',
            field=models.SmallIntegerField(choices=[(4, '服务器'), (1, '机房基础设备'), (3, '监播设备'), (2, 'IP网络设备')], verbose_name='分项类型'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(1, '在线'), (4, '报废'), (3, '维修'), (5, '待入库'), (2, '在库')], verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_total_type',
            field=models.SmallIntegerField(choices=[(2, '软件'), (3, '其他'), (1, '硬件')], verbose_name='总体类型'),
        ),
    ]
