# Generated by Django 4.0.3 on 2022-08-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_contract_warehouse_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_detail_type',
            field=models.SmallIntegerField(choices=[(2, 'IP网络设备'), (3, '监播设备'), (1, '机房基础设备'), (4, '服务器'), (5, '软件')], verbose_name='分项类型'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(2, '在库'), (3, '维修'), (1, '在线'), (4, '报废'), (5, '待入库')], verbose_name='当前状态'),
        ),
    ]
