# Generated by Django 4.0.3 on 2022-09-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_assets_assets_detail_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='assets_detail_type',
            field=models.SmallIntegerField(choices=[(1, '机房基础设备'), (2, 'IP网络设备'), (3, '监播设备'), (4, '服务器'), (5, '软件')], verbose_name='分项类型'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_status',
            field=models.SmallIntegerField(choices=[(1, '在线'), (2, '在库'), (3, '维修'), (4, '报废'), (5, '待入库')], verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='assets_total_type',
            field=models.SmallIntegerField(choices=[('1', '硬件'), ('2', '软件'), ('3', '其他')], verbose_name='总体类型'),
        ),
    ]
