# Generated by Django 4.0.3 on 2022-09-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_alter_assets_assets_detail_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(max_length=20, verbose_name='合同名称'),
        ),
    ]
