# Generated by Django 4.0.3 on 2022-09-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_alter_contract_contract_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='project_id',
            field=models.IntegerField(default=1, verbose_name='项目ID'),
            preserve_default=False,
        ),
    ]
