# Generated by Django 4.0.3 on 2022-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_alter_assets_assets_total_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='key_file',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='关键资料'),
        ),
    ]
