# Generated by Django 4.0.3 on 2022-09-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_file_key_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='now_schedule',
        ),
    ]
