# Generated by Django 4.0.3 on 2022-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_remove_project_now_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_tag',
            field=models.SmallIntegerField(choices=[(1, '普通任务'), (2, '二十大冲刺任务')], default=1, verbose_name='任务标签'),
            preserve_default=False,
        ),
    ]
