# Generated by Django 4.0.3 on 2022-09-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_task_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.SmallIntegerField(choices=[(1, '管理员'), (2, '普通用户'), (3, '二十大冲刺')], verbose_name='角色'),
        ),
    ]
