# Generated by Django 4.0.3 on 2022-11-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_alter_task_task_tag_alter_user_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_tag',
            field=models.SmallIntegerField(choices=[(1, '亚运任务'), (2, '日常任务')], verbose_name='任务标签'),
        ),
    ]
