# Generated by Django 4.0.3 on 2023-02-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_alter_task_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.SmallIntegerField(choices=[(1, '前端运维部'), (2, '网络管理部'), (3, '传输部'), (4, '网管中心'), (5, '安全播出部'), (6, '技术运维部')], verbose_name='负责部门'),
        ),
    ]
