# Generated by Django 4.0.3 on 2023-02-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0030_alter_project_project_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已发生额'),
        ),
    ]
