# Generated by Django 4.0.3 on 2023-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_alter_project_amount_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_used',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='已发生额'),
        ),
    ]
