# Generated by Django 4.0.3 on 2023-05-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0036_alter_task_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.SmallIntegerField(choices=[(1, '原前端运维部'), (2, '原网络管理部'), (3, '原传输部'), (4, '原网管中心'), (5, '原安全播出部'), (6, '前端运维中心'), (7, '系统技术部'), (8, '前端运行部'), (9, '技术管理部'), (10, '平台技术中心'), (11, '基础运维中心'), (12, '信息技术中心'), (13, '前端运维中心/基础运维中心')], verbose_name='负责部门'),
        ),
    ]
