# Generated by Django 4.0.3 on 2023-05-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0037_alter_task_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SmallIntegerField(choices=[(1, '工作会议'), (2, '预案更新'), (3, '检测维护'), (4, '演练'), (5, '培训考核'), (6, '亚运建设')], verbose_name='任务类型'),
        ),
    ]
