# Generated by Django 4.0.4 on 2023-06-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0042_alter_task_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_depart', models.SmallIntegerField(choices=[(1, '前端运行部'), (2, '系统技术部'), (3, '技术管理部')], verbose_name='文档部门')),
                ('data_name', models.CharField(max_length=20, verbose_name='文档名称')),
                ('data_type', models.CharField(choices=[(1, '技术文档'), (2, '演练文档'), (3, '应急预案'), (4, '巡检规范'), (5, '故障处理'), (6, '操作手册')], max_length=20, verbose_name='文档类型')),
                ('data_used', models.CharField(max_length=20, verbose_name='所有人')),
                ('data_time', models.DateField(verbose_name='提交时间')),
                ('explain', models.CharField(blank=True, max_length=20, null=True, verbose_name='备注')),
            ],
        ),
    ]
